# fly.toml app configuration file generated for arroyo-fly on 2024-07-31T17:12:45-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'arroyo-fly'
primary_region = 'sjc'

[build]
  image = 'ghcr.io/arroyosystems/arroyo:0.11'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']


[experimental]
cmd = ["run"]


[env]
  ARROYO__RUN__STATE_DIR = "s3::https://fly.storage.tigris.dev:443/empty-star-1118/top-editors"
  ARROYO__API__RUN_HTTP_PORT = 8000
  RUST_LOG = "info"

[[vm]]
  size = 'shared-cpu-1x'
